# Spring properties
spring:
  application:
    name: billing-service
  cloud:
    stream:
      bindings:
        bookingOrderInput:
          destination: amp.bookingOrdered
          consumer:
            resetOffsets: true
            headerMode: raw
          group: ${bookingConsumerGroup}
        billingOutput:
          destination: amp.billing
          contentType: application/*+avro
      schema:
        avro:
          schema-locations: classpath*:avro/billingOrder.avsc
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost

bookingConsumerGroup: "booking-service"


server:
  port: 2229



